import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import  { Toaster } from 'react-hot-toast'

import ThemeProviderNoSSR from '@/components/ThemeProviderNoSSR'
// attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange
const ddjbt = localFont({
  src: './fonts/DingTalkJinBuTi.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Xwya 后台管理系统',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body className={`${ddjbt.className}  antialiased`}>
        <ThemeProviderNoSSR attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
          <Toaster />
        </ThemeProviderNoSSR>
      </body>
    </html>
  )
}
