import type { Metadata } from 'next'
import localFont from 'next/font/local'
// import { ThemeProvider } from 'next-themes'
import './globals.css'


const ddjbt = localFont({
  src: './fonts/DingTalkJinBuTi.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})


export const metadata: Metadata = {
  title: 'Xwya 后台管理系统',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" >
      <body className={`${ddjbt.className}  antialiased`}>
        {/* <ThemeProviderNoSSR attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange> */}
          {children}
          {/* </ThemeProviderNoSSR> */}
      </body>
    </html>
  )
}
